From itsafeaturemythic/xgolang_payload:0.0.7
RUN go get github.com/djherbis/atime
RUN python3 -m pip uninstall -y mythic_payloadtype_container
RUN python3 -m pip install mythic_payloadtype_container==0.0.38
