// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: dns.proto

package dnsgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actions int32

const (
	Actions_AgentToServer Actions = 0
	Actions_ServerToAgent Actions = 1
	Actions_ReTransmit    Actions = 2
	Actions_MessageLost   Actions = 3
)

// Enum value maps for Actions.
var (
	Actions_name = map[int32]string{
		0: "AgentToServer",
		1: "ServerToAgent",
		2: "ReTransmit",
		3: "MessageLost",
	}
	Actions_value = map[string]int32{
		"AgentToServer": 0,
		"ServerToAgent": 1,
		"ReTransmit":    2,
		"MessageLost":   3,
	}
)

func (x Actions) Enum() *Actions {
	p := new(Actions)
	*p = x
	return p
}

func (x Actions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actions) Descriptor() protoreflect.EnumDescriptor {
	return file_dns_proto_enumTypes[0].Descriptor()
}

func (Actions) Type() protoreflect.EnumType {
	return &file_dns_proto_enumTypes[0]
}

func (x Actions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actions.Descriptor instead.
func (Actions) EnumDescriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

type DnsPacket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         Actions                `protobuf:"varint,1,opt,name=Action,proto3,enum=dnsStructs.Actions" json:"Action,omitempty"`
	AgentSessionID uint32                 `protobuf:"varint,2,opt,name=AgentSessionID,proto3" json:"AgentSessionID,omitempty"`
	MessageID      uint32                 `protobuf:"varint,3,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	TotalChunks    uint32                 `protobuf:"varint,4,opt,name=TotalChunks,proto3" json:"TotalChunks,omitempty"`
	CurrentChunk   uint32                 `protobuf:"varint,5,opt,name=CurrentChunk,proto3" json:"CurrentChunk,omitempty"`
	Data           []byte                 `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DnsPacket) Reset() {
	*x = DnsPacket{}
	mi := &file_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsPacket) ProtoMessage() {}

func (x *DnsPacket) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsPacket.ProtoReflect.Descriptor instead.
func (*DnsPacket) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

func (x *DnsPacket) GetAction() Actions {
	if x != nil {
		return x.Action
	}
	return Actions_AgentToServer
}

func (x *DnsPacket) GetAgentSessionID() uint32 {
	if x != nil {
		return x.AgentSessionID
	}
	return 0
}

func (x *DnsPacket) GetMessageID() uint32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *DnsPacket) GetTotalChunks() uint32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *DnsPacket) GetCurrentChunk() uint32 {
	if x != nil {
		return x.CurrentChunk
	}
	return 0
}

func (x *DnsPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dns_proto protoreflect.FileDescriptor

const file_dns_proto_rawDesc = "" +
	"\n" +
	"\tdns.proto\x12\n" +
	"dnsStructs\"\xd8\x01\n" +
	"\tDnsPacket\x12+\n" +
	"\x06Action\x18\x01 \x01(\x0e2\x13.dnsStructs.ActionsR\x06Action\x12&\n" +
	"\x0eAgentSessionID\x18\x02 \x01(\rR\x0eAgentSessionID\x12\x1c\n" +
	"\tMessageID\x18\x03 \x01(\rR\tMessageID\x12 \n" +
	"\vTotalChunks\x18\x04 \x01(\rR\vTotalChunks\x12\"\n" +
	"\fCurrentChunk\x18\x05 \x01(\rR\fCurrentChunk\x12\x12\n" +
	"\x04Data\x18\x06 \x01(\fR\x04Data*P\n" +
	"\aActions\x12\x11\n" +
	"\rAgentToServer\x10\x00\x12\x11\n" +
	"\rServerToAgent\x10\x01\x12\x0e\n" +
	"\n" +
	"ReTransmit\x10\x02\x12\x0f\n" +
	"\vMessageLost\x10\x03BVZTgithub.com/MythicAgents/poseidon/Payload_Type/poseidon/poseidon/pkg/profiles/dnsgrpcb\x06proto3"

var (
	file_dns_proto_rawDescOnce sync.Once
	file_dns_proto_rawDescData []byte
)

func file_dns_proto_rawDescGZIP() []byte {
	file_dns_proto_rawDescOnce.Do(func() {
		file_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)))
	})
	return file_dns_proto_rawDescData
}

var file_dns_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dns_proto_goTypes = []any{
	(Actions)(0),      // 0: dnsStructs.Actions
	(*DnsPacket)(nil), // 1: dnsStructs.DnsPacket
}
var file_dns_proto_depIdxs = []int32{
	0, // 0: dnsStructs.DnsPacket.Action:type_name -> dnsStructs.Actions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dns_proto_init() }
func file_dns_proto_init() {
	if File_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dns_proto_goTypes,
		DependencyIndexes: file_dns_proto_depIdxs,
		EnumInfos:         file_dns_proto_enumTypes,
		MessageInfos:      file_dns_proto_msgTypes,
	}.Build()
	File_dns_proto = out.File
	file_dns_proto_goTypes = nil
	file_dns_proto_depIdxs = nil
}
